version: "2"
services:
  # Backend
  express-server:
    build:
      context: ./express-server
    depends_on:
      - collector
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4318
  # Collector
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './otel-collector-config.yaml:/otel-collector-config.yaml'
    ports:
      - "4318:4318"
    depends_on:
      - jaeger-all-in-one
  # Jaeger
  jaeger-all-in-one:
    hostname: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16685"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true