receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]
          
exporters: 
  otlp:
    endpoint: "your are wavefront endpoint:port"
    tls:
      insecure: true
  logging:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [otlp, logging]
      processors: [batch]